[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd web && npm install --include=dev"]

[phases.build]
cmds = ["cd web && npm run build"]

[start]
cmd = "cd web && chmod +x start.sh && npm start"

